name: Merge upstream
on:
  schedule:
    - cron: '0 0 * * 1'  # Every monday UTC 0:00 (JST 9:00)

jobs:
  merge_upstream:
    name: Create merge upstream PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/ros/rosdistro.git
          git fetch upstream
      - name: Create upstream merge branch
        run: |
          git checkout -b merge-upstream-$(date '+%Y-%m-%d')
          git merge --no-ff --no-edit upstream/master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.SQBOT_GITHUB_TOKEN }}
          destination_branch: alpine-custom-apk
          pr_title: Merge upstream
